#!/usr/bin/env python3
"""Regenerate the native export codec registry labels from pinned CPython.

This is a build-time provenance/check helper, not a runtime dependency of the
proxy.  It asks the installed CPython registry which alias spellings resolve
through ``codecs.lookup`` and emits the normalized labels consumed by the Rust
exporter.  Use the repository's pinned Python environment for reproducible
output::

    .venv/bin/python proxy/tools/generate_export_codec_tables.py --check
    .venv/bin/python proxy/tools/generate_export_codec_tables.py --write

The alias names originate in CPython's ``encodings.aliases`` module.  That
module is distributed under the Python Software Foundation License 2.0; this
file copies only the resolved label strings, not CPython codec implementation.
"""

import argparse
import codecs
import encodings.aliases
import hashlib
import json
import sys
from pathlib import Path

from generate_export_big5 import validate_data

OUTPUT = Path(__file__).resolve().parents[1] / "src/traffic_view/codec_tables.rs"
BIG5_DATA = Path(__file__).with_name("export_big5_corrections.json")


def normalize(label: str) -> str:
    """Match normalize_python_codec_label in the Rust exporter."""
    output: list[str] = []
    separator = False
    for byte in label.encode("ascii"):
        if 0x30 <= byte <= 0x39 or 0x41 <= byte <= 0x5A or 0x61 <= byte <= 0x7A:
            if separator and output:
                output.append("-")
            output.append(chr(byte).lower())
            separator = False
        elif byte == ord("."):
            if separator and output:
                output.append("-")
            output.append(".")
            separator = False
        else:
            separator = True
    return "".join(output)


def labels() -> list[str]:
    resolved = set(encodings.aliases.aliases)
    resolved.update(encodings.aliases.aliases.values())
    output = set()
    for label in resolved:
        try:
            codecs.lookup(label)
        except LookupError:
            continue
        output.add(normalize(label))
    return sorted(output)


def source_sha256() -> str:
    return hashlib.sha256(Path(encodings.aliases.__file__).read_bytes()).hexdigest()


def big5_corrections() -> list[dict[str, str]]:
    data = json.loads(BIG5_DATA.read_text())
    validate_data(data)
    return data["corrections"]


def render() -> str:
    source = Path(encodings.aliases.__file__).name
    values = "\n".join(f'    "{label}",' for label in labels())
    corrections = "\n".join(
        f"    (0x{item['bytes']}, '\\u{{{item['codepoint'][2:].lower()}}}'),"
        for item in big5_corrections()
    )
    return f'''//! @generated by proxy/tools/generate_export_codec_tables.py.
//!
//! Source: CPython {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}
//! `encodings.aliases` ({source}), SHA-256 {source_sha256()}.
//! The alias data is covered by the Python Software Foundation License 2.0;
//! this generated file contains normalized labels and source-derived Big5
//! corrections, not codec code.

const PYTHON_CODEC_LABELS: &[&str] = &[
{values}
];

// CPython 3.12.14 Big5 mappings absent from encoding_rs 0.8.41.  The compact
// source data and reproducible comparison are maintained by
// proxy/tools/generate_export_big5.py.
const BIG5_CORRECTIONS: &[(u16, char)] = &[
{corrections}
];

pub(super) fn big5_correction(first: u8, second: u8) -> Option<char> {{
    let key = u16::from_be_bytes([first, second]);
    BIG5_CORRECTIONS
        .binary_search_by_key(&key, |(key, _)| *key)
        .ok()
        .map(|index| BIG5_CORRECTIONS[index].1)
}}

pub(super) fn python_codec_is_registered(label: &str) -> bool {{
    PYTHON_CODEC_LABELS.binary_search(&label).is_ok()
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = render()
    actual = OUTPUT.read_text() if OUTPUT.exists() else None
    if args.write:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT} ({len(labels())} labels)")
        return 0
    if actual != expected:
        print(f"{OUTPUT} differs; run this script with --write", file=sys.stderr)
        return 1
    print(f"matched {OUTPUT} ({len(labels())} labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
