"""Pytest fixtures for host-side blackbox tests.

These tests run on the HOST, not inside the VM. The host has direct
access to the sinkhole control API (localhost:19999), admin API
(localhost:9090), and the proxy (localhost:8080). No firewall in the way.

proxy_client works from the host because credential_guard evaluates
based on request content (headers, host), not source IP.
"""

import os
import sys
import time
from pathlib import Path

import httpx
import pytest
from sinkhole_client import SinkholeClient

# Import the shared docstring linter from the parent blackbox dir.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _docstring_lint import validate_items  # noqa: E402


def pytest_collection_modifyitems(config, items):
    """Reject collection if any test's docstring is missing structure.

    Schema lives in tests/blackbox/_docstring_lint.py and is shared
    with the isolation suite and docs/blackbox-coverage.md generator.
    """
    validate_items(items)

# ---------------------------------------------------------------------------
# Host-side configuration — everything on localhost
# ---------------------------------------------------------------------------
PROXY_URL = os.environ.get("PROXY_URL", "http://127.0.0.1:8080")
ADMIN_URL = os.environ.get("ADMIN_URL", "http://127.0.0.1:9090")
SINKHOLE_API = os.environ.get("SINKHOLE_API", "http://127.0.0.1:19999")

# Paths respect SAFEYOLO_CONFIG_DIR so tests work against an isolated instance
_CONFIG_DIR = Path(os.environ.get("SAFEYOLO_CONFIG_DIR", str(Path.home() / ".safeyolo")))

# Admin token: read from file (generated by proxy on startup)
_ADMIN_TOKEN_PATH = _CONFIG_DIR / "data" / "admin_token"
ADMIN_TOKEN = os.environ.get("ADMIN_API_TOKEN", "")
if not ADMIN_TOKEN and _ADMIN_TOKEN_PATH.exists():
    ADMIN_TOKEN = _ADMIN_TOKEN_PATH.read_text().strip()

# Mitmproxy CA cert for TLS verification (ground truth, not verify=False)
_CA_CERT = _CONFIG_DIR / "certs" / "mitmproxy-ca-cert.pem"

# ---------------------------------------------------------------------------
# Test credentials — MUST match production detection patterns
# ---------------------------------------------------------------------------
# OpenAI pattern: sk-proj-[a-zA-Z0-9_-]{80,}
TEST_OPENAI_KEY = "sk-proj-" + "a1b2c3d4e5f6g7h8i9j0" * 4

# Anthropic pattern: sk-ant-api[a-zA-Z0-9-]{90,}
TEST_ANTHROPIC_KEY = "sk-ant-api03-" + "a1b2c3d4e5f6g7h8i9j0" * 5

# GitHub pattern: gh[ps]_[a-zA-Z0-9]{36}
TEST_GITHUB_TOKEN = "ghp_" + "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture(scope="session")
def sinkhole():
    """Sinkhole client for request inspection (host-side, localhost)."""
    client = SinkholeClient(SINKHOLE_API)
    try:
        client.wait_for_ready(timeout=10)
    except Exception:
        pytest.skip("Sinkhole not available")
    yield client
    client.close()


@pytest.fixture(scope="session")
def admin_headers():
    """Headers for admin API authentication."""
    return {"Authorization": f"Bearer {ADMIN_TOKEN}"}


@pytest.fixture(scope="session")
def admin_client(admin_headers):
    """HTTP client for admin API (host-side, localhost)."""
    client = httpx.Client(
        base_url=ADMIN_URL,
        headers=admin_headers,
        timeout=10.0,
    )
    yield client
    client.close()


@pytest.fixture(scope="session")
def proxy_client():
    """HTTP client that routes through SafeYolo proxy.

    Uses the mitmproxy CA cert for TLS verification when available.
    Falls back to unverified if cert not found.
    """
    if _CA_CERT.exists():
        import ssl
        ctx = ssl.create_default_context(cafile=str(_CA_CERT))
        verify = ctx
    else:
        verify = False
    client = httpx.Client(
        proxy=PROXY_URL,
        verify=verify,
        timeout=30.0,
    )
    yield client
    client.close()


@pytest.fixture
def clear_sinkhole(sinkhole):
    """Clear sinkhole before each test for isolation."""
    sinkhole.clear_requests()
    yield


@pytest.fixture(scope="session")
def wait_for_safeyolo(admin_client):
    """Ensure SafeYolo proxy is ready."""
    for attempt in range(60):
        try:
            resp = admin_client.get("/health")
            if resp.status_code == 200:
                break
        except httpx.RequestError:
            pass
        time.sleep(1)
    else:
        pytest.fail("SafeYolo admin API not ready after 60 seconds")
    yield


@pytest.fixture(scope="session")
def wait_for_services(sinkhole, wait_for_safeyolo):
    """Ensure all services are ready before tests run."""
    yield
