"""Pytest fixtures for host-side blackbox tests.

These tests run on the HOST, not inside the VM. The host has direct
access to the sinkhole control API (localhost:19999) and the admin
API (localhost:ADMIN_PORT). The proxy no longer listens on TCP — it
binds per-agent Unix domain sockets under `$SAFEYOLO_CONFIG_DIR/data/
sockets/<ip>_<agent>.sock`. `proxy_client` provisions a test listener
at session start via `PUT /admin/proxy/mode` and speaks to mitmproxy
through that UDS.

proxy_client works from the host because credential_guard evaluates
based on request content (headers, host), not source IP.
"""

import os
import sys
import time
from pathlib import Path

import httpx
import pytest

# host/ is this conftest's directory — sinkhole_client.py and
# uds_transport.py live here. When pytest is invoked against a
# subdirectory (e.g. `pytest proxy/`), the subdir gets injected into
# sys.path but host/ does not, so the bare imports below would fail.
# Inject host/ explicitly so they work regardless of invocation cwd.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from sinkhole_client import SinkholeClient  # noqa: E402
from uds_transport import UDSProxyTransport  # noqa: E402

# Import the shared docstring linter from the parent blackbox dir.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _docstring_lint import validate_items  # noqa: E402


def pytest_collection_modifyitems(config, items):
    """Reject collection if any test's docstring is missing structure.

    Schema lives in tests/blackbox/_docstring_lint.py and is shared
    with the isolation suite and docs/blackbox-coverage.md generator.
    """
    validate_items(items)

# ---------------------------------------------------------------------------
# Host-side configuration — everything on localhost
# ---------------------------------------------------------------------------
ADMIN_URL = os.environ.get("ADMIN_URL", "http://127.0.0.1:9090")
SINKHOLE_API = os.environ.get("SINKHOLE_API", "http://127.0.0.1:19999")

# Session-scoped test agent: bbproxy on an IP outside the default
# 10.200.0.0/16 range used by real agents. Keeps the blackbox-provisioned
# UDS distinct from anything production might create while the test
# instance is alive.
_TEST_AGENT_NAME = os.environ.get("SAFEYOLO_BBTEST_PROXY_AGENT", "bbproxy")
_TEST_AGENT_IP = os.environ.get("SAFEYOLO_BBTEST_PROXY_IP", "10.200.255.1")

# Paths respect SAFEYOLO_CONFIG_DIR so tests work against an isolated instance
_CONFIG_DIR = Path(os.environ.get("SAFEYOLO_CONFIG_DIR", str(Path.home() / ".safeyolo")))

# Admin token: read from file (generated by proxy on startup)
_ADMIN_TOKEN_PATH = _CONFIG_DIR / "data" / "admin_token"
ADMIN_TOKEN = os.environ.get("ADMIN_API_TOKEN", "")
if not ADMIN_TOKEN and _ADMIN_TOKEN_PATH.exists():
    ADMIN_TOKEN = _ADMIN_TOKEN_PATH.read_text().strip()

# Mitmproxy CA cert for TLS verification (ground truth, not verify=False)
_CA_CERT = _CONFIG_DIR / "certs" / "mitmproxy-ca-cert.pem"

# ---------------------------------------------------------------------------
# Test credentials — MUST match production detection patterns
# ---------------------------------------------------------------------------
# OpenAI pattern: sk-proj-[a-zA-Z0-9_-]{80,}
TEST_OPENAI_KEY = "sk-proj-" + "a1b2c3d4e5f6g7h8i9j0" * 4

# Anthropic pattern: sk-ant-api[a-zA-Z0-9-]{90,}
TEST_ANTHROPIC_KEY = "sk-ant-api03-" + "a1b2c3d4e5f6g7h8i9j0" * 5

# GitHub pattern: gh[ps]_[a-zA-Z0-9]{36}
TEST_GITHUB_TOKEN = "ghp_" + "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------
@pytest.fixture(scope="session")
def sinkhole():
    """Sinkhole client for request inspection (host-side, localhost)."""
    client = SinkholeClient(SINKHOLE_API)
    try:
        client.wait_for_ready(timeout=10)
    except Exception:
        pytest.skip("Sinkhole not available")
    yield client
    client.close()


@pytest.fixture(scope="session")
def admin_headers():
    """Headers for admin API authentication."""
    return {"Authorization": f"Bearer {ADMIN_TOKEN}"}


@pytest.fixture(scope="session")
def admin_client(admin_headers):
    """HTTP client for admin API (host-side, localhost)."""
    client = httpx.Client(
        base_url=ADMIN_URL,
        headers=admin_headers,
        timeout=10.0,
    )
    yield client
    client.close()


@pytest.fixture(scope="session")
def proxy_uds_path(admin_client, wait_for_safeyolo):
    """Provision a per-session UDS listener via admin PUT.

    Side-steps `safeyolo agent add`, which would try to boot a VM.
    The test instance's mitmproxy creates the socket file as soon as
    `options.mode` gets an entry referring to it (bootstrap_mode /
    admin PUT both take this path).

    The listener is torn down in teardown so nothing lingers between
    blackbox runs.
    """
    sockets_dir = _CONFIG_DIR / "data" / "sockets"
    sockets_dir.mkdir(parents=True, exist_ok=True)
    uds_path = sockets_dir / f"{_TEST_AGENT_IP}_{_TEST_AGENT_NAME}.sock"
    spec = f"unix:{uds_path}"

    # The blackbox test instance starts with agent_map.json empty
    # (run-tests.sh clears $CONFIG_DIR/agents/ before start), so the
    # proxy's mode list is [] at this point. Replacing it outright is
    # simpler — and safer — than trying to merge.
    resp = admin_client.put("/admin/proxy/mode", json={"modes": [spec]})
    assert resp.status_code == 200, f"PUT /admin/proxy/mode failed: {resp.text}"

    # Wait for the Servers addon to actually bind the socket. The PUT
    # handler already sleeps 0.5s to let reconcile finish; the poll
    # here absorbs slow CI hosts without flaking.
    deadline = time.monotonic() + 10.0
    while time.monotonic() < deadline:
        if uds_path.is_socket():
            break
        time.sleep(0.1)
    else:
        raise RuntimeError(
            f"Test UDS listener did not appear at {uds_path} within 10s"
        )

    yield uds_path

    # Best-effort teardown — `run-tests.sh` also does `safeyolo stop`.
    try:
        admin_client.put("/admin/proxy/mode", json={"modes": []})
    except httpx.RequestError:
        pass


@pytest.fixture(scope="session")
def proxy_client(proxy_uds_path):
    """HTTP client that routes through SafeYolo proxy via UDS.

    Uses the mitmproxy CA cert for TLS verification when available —
    blackbox tests assert ground-truth chain validation, never verify=False.
    """
    ca_cert = _CA_CERT if _CA_CERT.exists() else None
    transport = UDSProxyTransport(proxy_uds_path, ca_cert=ca_cert)
    verify_arg = str(_CA_CERT) if ca_cert else False
    client = httpx.Client(
        transport=transport,
        verify=verify_arg,
        timeout=30.0,
    )
    yield client
    client.close()


@pytest.fixture
def clear_sinkhole(sinkhole):
    """Clear sinkhole before each test for isolation."""
    sinkhole.clear_requests()
    yield


@pytest.fixture(scope="session")
def wait_for_safeyolo(admin_client):
    """Ensure SafeYolo proxy is ready."""
    for attempt in range(60):
        try:
            resp = admin_client.get("/health")
            if resp.status_code == 200:
                break
        except httpx.RequestError:
            pass
        time.sleep(1)
    else:
        pytest.fail("SafeYolo admin API not ready after 60 seconds")
    yield


@pytest.fixture(scope="session")
def wait_for_services(sinkhole, wait_for_safeyolo):
    """Ensure all services are ready before tests run."""
    yield
