"""
service_gateway.py - Service Gateway addon for credential injection

Intercepts requests with sgw_ gateway tokens, validates route whitelists,
strips the gateway token, and injects real credentials from the vault.

Agents use real hostnames with existing SDKs (zero code changes) but never
see real credentials. The gateway holds credentials and injects them.

Flow:
  Agent sends Authorization: Bearer sgw_abc123... to gmail.googleapis.com
  → proxy intercepts → validates route whitelist → strips sgw_ token
  → injects real OAuth token from vault → forwards upstream.

Loading order: Layer 0.5, between policy_engine and network_guard.
Does NOT inherit SecurityAddon - follows AgentRelay pattern.

Usage:
    mitmdump -s addons/service_gateway.py \\
        --set gateway_enabled=true \\
        --set gateway_services_dir=/safeyolo/services \\
        --set gateway_vault_path=/safeyolo/data/vault.yaml.enc
"""

import logging
import secrets
import threading
from dataclasses import dataclass, field
from pathlib import Path

from mitmproxy import ctx, http
from service_loader import get_service_registry
from utils import make_block_response, matches_resource_pattern, write_event
from vault import get_vault

log = logging.getLogger("safeyolo.service-gateway")

# Token prefix for gateway tokens
SGW_TOKEN_PREFIX = "sgw_"
SGW_TOKEN_LEN = 64  # hex chars after prefix


@dataclass
class TokenBinding:
    """Maps a gateway token to an agent/service/role + vault credential."""
    agent: str
    service_name: str
    role_name: str
    vault_token: str  # vault credential name


@dataclass
class GatewayStats:
    """Statistics for the gateway."""
    requests: int = 0
    injected: int = 0
    denied_route: int = 0
    denied_token: int = 0
    refreshed: int = 0
    tokens_registered: int = 0


def mint_gateway_token() -> str:
    """Generate a new gateway token."""
    return f"{SGW_TOKEN_PREFIX}{secrets.token_hex(SGW_TOKEN_LEN // 2)}"


class ServiceGateway:
    """Service Gateway addon - credential injection for agents.

    Follows AgentRelay pattern (not SecurityAddon). Positioned between
    policy_engine and network_guard in the addon chain.
    """

    name = "service-gateway"

    def __init__(self):
        self._token_map: dict[str, TokenBinding] = {}
        self._host_map: dict[str, str] = {}
        self._lock = threading.RLock()
        self.stats = GatewayStats()

    def load(self, loader):
        loader.add_option(
            name="gateway_enabled",
            typespec=bool,
            default=False,
            help="Enable the service gateway for credential injection",
        )
        loader.add_option(
            name="gateway_services_dir",
            typespec=str,
            default="/safeyolo/services",
            help="Directory containing service definition YAML files",
        )
        loader.add_option(
            name="gateway_vault_path",
            typespec=str,
            default="/safeyolo/data/vault.yaml.enc",
            help="Path to encrypted vault file",
        )
        loader.add_option(
            name="gateway_vault_key",
            typespec=str,
            default="/safeyolo/data/vault.key",
            help="Path to vault key file (auto-generated by CLI)",
        )

    def configure(self, updates):
        if not ctx.options.gateway_enabled:
            return

        if "gateway_enabled" in updates or "gateway_services_dir" in updates:
            self._init_services()

        if "gateway_enabled" in updates or "gateway_vault_path" in updates:
            self._init_vault()

        # Mint tokens when gateway enables (policy is already loaded by then)
        if "gateway_enabled" in updates:
            self._mint_tokens_from_policy()

    def _init_services(self):
        """Initialize service registry from service definition files."""
        try:
            from service_loader import init_service_registry

            user_dir = Path(ctx.options.gateway_services_dir)
            registry = init_service_registry(user_dir)
            registry.start_watcher()
            log.info(f"Service registry loaded from {user_dir}")
        except Exception as e:
            log.error(f"Failed to load service registry: {type(e).__name__}: {e}")

    def _init_vault(self):
        """Initialize vault from encrypted file, using auto-generated key file."""
        key_path = Path(ctx.options.gateway_vault_key)
        vault_path = Path(ctx.options.gateway_vault_path)

        if not key_path.exists():
            log.info(f"Gateway vault key not found at {key_path} — vault disabled")
            return

        if not vault_path.exists():
            log.info(f"Gateway vault not found at {vault_path} — vault disabled")
            return

        try:
            from vault import init_vault
            key = key_path.read_text().strip()
            vault = init_vault(vault_path, key)
            vault.start_watcher()
            log.info("Vault unlocked")
        except Exception as e:
            log.error(f"Failed to unlock vault: {type(e).__name__}: {e}")

    def _mint_tokens_from_policy(self):
        """Read agents section from compiled policy and mint gateway tokens."""
        try:
            from pdp import get_policy_client, is_policy_client_configured

            if not is_policy_client_configured():
                log.debug("PolicyClient not configured yet, skipping token minting")
                return

            client = get_policy_client()
            gateway_config = client.get_gateway_config()
            if not gateway_config:
                log.debug("No gateway config in policy (no agents: section?)")
                return

            token_map = gateway_config.get("token_map", {})
            agent_env = gateway_config.get("agent_env", {})
            self._host_map = gateway_config.get("host_map", {})

            if not token_map:
                return

            # Rebuild token map from policy — convert dicts to TokenBinding
            with self._lock:
                self._token_map.clear()
                self.stats.tokens_registered = 0
                for token, binding in token_map.items():
                    self._token_map[token] = TokenBinding(
                        agent=binding["agent"],
                        service_name=binding["service"],
                        role_name=binding["role"],
                        vault_token=binding["token"],
                    )
                    self.stats.tokens_registered += 1

            log.info(f"Minted {self.stats.tokens_registered} tokens from policy for agents: {list(agent_env.keys())}")

        except Exception as e:
            log.error(f"Failed to mint tokens from policy: {type(e).__name__}: {e}")

    def done(self):
        """Clean shutdown — stop file watchers."""
        registry = get_service_registry()
        if registry:
            registry.stop_watcher()
        vault = get_vault()
        if vault:
            vault.stop_watcher()

    def running(self):
        if ctx.options.gateway_enabled:
            log.info(f"Service gateway active ({self.stats.tokens_registered} tokens registered)")
        else:
            log.info("Service gateway disabled")

    def request(self, flow: http.HTTPFlow):
        """Intercept requests with sgw_ gateway tokens."""
        if not ctx.options.gateway_enabled:
            return

        # Already handled by another addon
        if flow.response:
            return

        # Extract sgw_ token from Authorization header
        token = self._extract_sgw_token(flow)
        if not token:
            return  # Not a gateway request - pass through

        self.stats.requests += 1

        # Lookup token binding
        with self._lock:
            binding = self._token_map.get(token)

        if not binding:
            self._deny(flow, 403, "Invalid gateway token", "INVALID_TOKEN")
            self.stats.denied_token += 1
            return

        # Validate agent matches (if service_discovery stamped flow.metadata["agent"])
        agent = flow.metadata.get("agent")
        if agent and agent != binding.agent:
            self._deny(flow, 403, f"Token not authorized for agent '{agent}'", "AGENT_MISMATCH")
            self.stats.denied_token += 1
            return

        # Get service and role
        registry = get_service_registry()
        if not registry:
            self._deny(flow, 503, "Service registry not available", "REGISTRY_UNAVAILABLE")
            return

        service = registry.get_service(binding.service_name)
        if not service:
            self._deny(flow, 403, f"Service '{binding.service_name}' not found", "SERVICE_NOT_FOUND")
            self.stats.denied_token += 1
            return

        role = service.roles.get(binding.role_name)
        if not role:
            self._deny(flow, 403, f"Role '{binding.role_name}' not found", "ROLE_NOT_FOUND")
            self.stats.denied_token += 1
            return

        # Validate host matches via host_map (policy binds host → service)
        expected_service = self._host_map.get(flow.request.host.lower())
        if expected_service != binding.service_name:
            self._deny(
                flow, 403,
                f"Host '{flow.request.host}' is not mapped to service '{binding.service_name}'",
                "HOST_MISMATCH",
            )
            self.stats.denied_token += 1
            return

        # Evaluate routes: deny-first
        path = flow.request.path.split("?")[0]  # Strip query string
        method = flow.request.method

        if not self._evaluate_routes(method, path, role.routes):
            self._deny(
                flow, 403,
                f"Route {method} {path} not allowed for role '{role.name}'",
                "ROUTE_DENIED",
            )
            self.stats.denied_route += 1
            return

        # Get real credential from vault (name comes from policy binding)
        vault = get_vault()
        if not vault:
            self._deny(flow, 503, "Vault not available", "VAULT_UNAVAILABLE")
            return

        cred = vault.get(binding.vault_token)
        if not cred:
            self._deny(flow, 503, f"Credential '{binding.vault_token}' not found in vault", "CREDENTIAL_NOT_FOUND")
            return

        # Auto-refresh OAuth2 if expired
        if cred.type == "oauth2" and cred.is_expired() and role.auth.refresh_on_401:
            if vault.refresh_oauth2(binding.vault_token):
                self.stats.refreshed += 1
                cred = vault.get(binding.vault_token)
                if not cred:
                    self._deny(flow, 503, "Credential lost after refresh", "CREDENTIAL_NOT_FOUND")
                    return

        # Strip sgw_ token and inject real credential
        del flow.request.headers["Authorization"]
        if role.auth.type == "bearer":
            flow.request.headers["Authorization"] = f"{role.auth.scheme} {cred.value}"
            injected_header = "Authorization"
        elif role.auth.type == "api_key":
            flow.request.headers[role.auth.header] = cred.value
            injected_header = role.auth.header

        # Stamp metadata
        flow.metadata["gateway_service"] = service.name
        flow.metadata["gateway_role"] = role.name
        flow.metadata["gateway_agent"] = binding.agent
        flow.metadata["gateway_injected_header"] = injected_header

        # Log allow event
        write_event(
            "broker.allow",
            request_id=flow.metadata.get("request_id"),
            addon=self.name,
            agent=binding.agent,
            service=service.name,
            role=role.name,
            host=flow.request.host,
            method=method,
            path=path,
        )

        self.stats.injected += 1

    def _extract_sgw_token(self, flow: http.HTTPFlow) -> str | None:
        """Extract sgw_ token from request headers."""
        auth = flow.request.headers.get("authorization", "")

        # Check Bearer token
        if auth.startswith("Bearer ") or auth.startswith("bearer "):
            token = auth[7:].strip()
            if token.startswith(SGW_TOKEN_PREFIX):
                return token

        # Check raw Authorization header
        if auth.startswith(SGW_TOKEN_PREFIX):
            return auth.strip()

        return None

    def _evaluate_routes(self, method: str, path: str, routes: list) -> bool:
        """Evaluate route rules: deny-first, then allow, default deny.

        Returns True if the request is allowed.
        """
        # Check deny rules first
        for rule in routes:
            if rule.effect != "deny":
                continue
            if self._method_matches(method, rule.methods) and matches_resource_pattern(path, rule.path):
                return False

        # Check allow rules
        for rule in routes:
            if rule.effect != "allow":
                continue
            if self._method_matches(method, rule.methods) and matches_resource_pattern(path, rule.path):
                return True

        # Default deny (fail closed)
        return False

    def _method_matches(self, method: str, allowed_methods: list[str]) -> bool:
        """Check if HTTP method matches allowed methods list."""
        if "*" in allowed_methods:
            return True
        return method.upper() in [m.upper() for m in allowed_methods]

    def _deny(self, flow: http.HTTPFlow, status: int, reason: str, code: str) -> None:
        """Block request with standard JSON response."""
        body = {
            "error": reason,
            "reason_codes": [code],
            "addon": self.name,
        }
        flow.response = make_block_response(status, body, self.name)
        flow.metadata["blocked_by"] = self.name

        write_event(
            "broker.deny",
            request_id=flow.metadata.get("request_id"),
            addon=self.name,
            agent=flow.metadata.get("agent"),
            host=flow.request.host,
            reason=reason,
            code=code,
        )

    def mint_tokens(self, agent_bindings: dict[str, dict[str, dict[str, str]]]) -> dict[str, dict[str, str]]:
        """Mint gateway tokens for agent/service bindings.

        Args:
            agent_bindings: {agent_name: {service_name: {"role": role_name, "token": vault_token}}}

        Returns:
            {agent_name: {ENV_VAR: sgw_token}}
        """
        agent_env: dict[str, dict[str, str]] = {}

        with self._lock:
            for agent, services in agent_bindings.items():
                agent_env[agent] = {}
                for service_name, config in services.items():
                    sgw_token = mint_gateway_token()
                    self._token_map[sgw_token] = TokenBinding(
                        agent=agent,
                        service_name=service_name,
                        role_name=config["role"],
                        vault_token=config["token"],
                    )
                    agent_env[agent][service_name] = sgw_token
                    self.stats.tokens_registered += 1

        log.info(f"Minted {self.stats.tokens_registered} gateway tokens")
        return agent_env

    def get_stats(self) -> dict:
        """Return stats for admin API (no secrets)."""
        with self._lock:
            bindings = []
            for binding in self._token_map.values():
                bindings.append({
                    "agent": binding.agent,
                    "service": binding.service_name,
                    "role": binding.role_name,
                })

        return {
            "requests": self.stats.requests,
            "injected": self.stats.injected,
            "denied_route": self.stats.denied_route,
            "denied_token": self.stats.denied_token,
            "refreshed": self.stats.refreshed,
            "tokens_registered": self.stats.tokens_registered,
            "bindings": bindings,
        }

    def get_agent_services(self) -> dict[str, dict[str, dict]]:
        """Return agent service bindings (host + token). For relay /gateway/services."""
        # Build reverse map: service_name → host
        reverse_host_map: dict[str, str] = {}
        for host, service_name in self._host_map.items():
            reverse_host_map[service_name] = host

        with self._lock:
            result: dict[str, dict[str, dict]] = {}
            for token, binding in self._token_map.items():
                host = reverse_host_map.get(binding.service_name, "")
                result.setdefault(binding.agent, {})[binding.service_name] = {
                    "host": host,
                    "token": token,
                }
            return result


addons = [ServiceGateway()]
