"""Host-side upstream TLS certificate validation tests.

Exercises SafeYolo's `_merge_system_cas_into_certifi` + mitmproxy's
upstream TLS chain builder against a range of non-trivial cert chain
shapes. Each shape below catches a distinct class of upstream-verify
regression -- happy-path shapes guard against over-strict validation
(false negatives); must-fail shapes guard against accepting bad certs
(false positives).

Background (why this suite exists):
    The real-world example.com leaf is served by Cloudflare with a
    chain that terminates at an SSL.com 2022 ECC root, optionally
    cross-signed by Comodo AAA as a bridge for older trust stores.
    SafeYolo has regressed upstream validation of that exact shape
    twice -- the fix each time was in the CA-bundle merge, but the
    symptom was "example.com returns 000 / hangs / verify failed".

Ground-truth, internet-free: the sinkhole stands up a family of HTTPS
endpoints on ports 18444-18450, each presenting a different synthetic
chain generated by certs/generate-certs.sh. If SafeYolo's bundle merge
breaks or the chain builder regresses in any of these dimensions, one
of the tests below turns red.

Adding new cert-shape cases: generate another chain in
generate-certs.sh, add a `--extra-cert` entry in run-tests.sh, add
a hostname + port mapping to harness/sinkhole_router.py, and drop a
test class here that curls through the proxy to that hostname.
"""

import httpx

# mitmproxy surfaces upstream TLS-verify failures as 502. Some client
# configurations (older httpx/openssl combinations) may raise a connect
# error instead -- both outcomes prove the chain was rejected, which is
# what these tests assert. The MUST_FAIL helper normalises both.
_UPSTREAM_REJECT_STATUS = 502


def _assert_upstream_rejected(proxy_client, url, hostname, sinkhole):
    """Perform a GET that must be rejected by upstream TLS verify.

    Accepts either a 502 from mitmproxy OR an httpx connect/read error
    (some TLS failures surface as stream-level rather than status-level
    errors). In both cases the sinkhole MUST NOT have recorded a request
    for the hostname -- if it did, mitmproxy accepted the bad cert and
    forwarded, which is the regression we're guarding against.
    """
    try:
        response = proxy_client.get(url, follow_redirects=False)
        assert response.status_code != 200, (
            f"REGRESSION: mitmproxy accepted a cert that MUST be rejected "
            f"(got 200 from {url}). Upstream cert validation is broken."
        )
        assert response.status_code == _UPSTREAM_REJECT_STATUS, (
            f"Expected 502 (upstream verify failure) or transport error for "
            f"{url}, got {response.status_code}."
        )
    except (httpx.ConnectError, httpx.ReadError, httpx.RemoteProtocolError):
        # Transport-level rejection is equally valid -- the important
        # property is that the bad cert did not get accepted.
        pass

    requests = sinkhole.get_requests(host=hostname)
    assert len(requests) == 0, (
        f"REGRESSION: sinkhole recorded {len(requests)} request(s) for "
        f"{hostname} -- mitmproxy accepted a cert that MUST be rejected "
        f"and forwarded the request upstream."
    )


class TestEccCrossSignedChain:
    """Upstream validation of an ECC leaf whose chain reaches the
    trusted root via a cross-signed bridge.

    Why: Mirrors example.com's shape. If certifi's bundle lacks a root
    the merge was supposed to supply, or the chain builder fails to
    traverse the bridge cert, validation drops and the curl hangs
    (the failure surfaces as time-out or 502 from mitmproxy).
    """

    def test_chain_validates_end_to_end(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://example-chain-test.test/ through the proxy returns 200.

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18444 HTTPS endpoint. The sinkhole presents the chain
        [ECC leaf, ECC intermediate, test-ca-b cross-signed by
        test-ca]. mitmproxy validates it against the merged bundle,
        accepts, MITMs, and forwards to us.
        Why: A green 200 confirms the chain-shape regression that
        has bitten us twice is not currently present. A red (timeout,
        502, or TLS verify error from mitmproxy) means something in
        `_merge_system_cas_into_certifi` or the upstream TLS context
        is broken.
        """
        response = proxy_client.get(
            "https://example-chain-test.test/",
            follow_redirects=False,
        )
        assert response.status_code == 200, (
            f"Expected 200 (sinkhole default), got {response.status_code}. "
            f"mitmproxy probably failed upstream chain validation -- check "
            f"~/.safeyolo-test/logs/mitmproxy.log for 'verify' / 'chain' errors."
        )

        # Confirm the sinkhole actually received it (guards against a
        # false positive where mitmproxy itself returned a non-upstream
        # response without forwarding).
        requests = sinkhole.get_requests(host="example-chain-test.test")
        assert len(requests) >= 1, (
            "Sinkhole saw no requests for example-chain-test.test. "
            "mitmproxy returned 200 without forwarding?"
        )


class TestRsaDeepChain:
    """Upstream validation of a 4-deep RSA chain (leaf -> intA -> intB -> root).

    Why: Many real-world CDN chains (Amazon CloudFront, Microsoft,
    some Akamai deployments) are 4-deep. Chain builder regressions
    around depth limits, path-length constraints, or intermediate
    caching surface here without needing public internet access.
    """

    def test_four_deep_chain_validates(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://rsa-deep-chain.test/ through the proxy returns 200.

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18445 HTTPS endpoint. The sinkhole presents the chain
        [RSA leaf, RSA intermediate A (pathlen:0), RSA intermediate B
        (pathlen:1)]. mitmproxy walks leaf -> A -> B -> ca.crt and
        accepts.
        Why: A green 200 confirms the chain builder handles 4-deep
        chains with path-length-constrained intermediates. A red means
        either the depth is being truncated, or the pathlen constraint
        is being misinterpreted -- both would break real CDN upstreams.
        """
        response = proxy_client.get(
            "https://rsa-deep-chain.test/",
            follow_redirects=False,
        )
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. mitmproxy failed "
            f"4-deep chain validation -- check logs for depth / pathlen errors."
        )
        requests = sinkhole.get_requests(host="rsa-deep-chain.test")
        assert len(requests) >= 1, (
            "Sinkhole saw no request for rsa-deep-chain.test."
        )


class TestNameConstrainedIntermediate:
    """Upstream validation of a leaf under a name-constrained intermediate.

    Why: X.509 nameConstraints (RFC 5280 s4.2.1.10) is implemented
    inconsistently across TLS stacks -- OpenSSL, Python ssl, and
    mitmproxy have each had bugs at various versions. An intermediate
    that permits DNS:nc-constrained.test must still validate a leaf
    whose SAN is within that subtree.
    """

    def test_leaf_in_permitted_subtree_validates(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://nc-constrained.test/ through the proxy returns 200.

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18446 HTTPS endpoint. The intermediate has critical
        nameConstraints permitting DNS:nc-constrained.test and
        IP:127.0.0.1. The leaf's SAN matches both constraints.
        Why: A green 200 confirms mitmproxy honours nameConstraints
        correctly when the leaf is within the permitted subtree. A red
        502 likely means the validator is rejecting leaves under
        name-constrained intermediates outright (a known bug class in
        some TLS stacks).
        """
        response = proxy_client.get(
            "https://nc-constrained.test/",
            follow_redirects=False,
        )
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. mitmproxy rejected "
            f"a leaf within the permitted subtree of its name-constrained "
            f"intermediate -- nameConstraints handling regression."
        )
        requests = sinkhole.get_requests(host="nc-constrained.test")
        assert len(requests) >= 1


class TestExtraIntermediatesIgnored:
    """Upstream validation when server presents extra, unrelated intermediates.

    Why: Real-world servers sometimes include extras in the chain due
    to SSLCertificateChainFile misconfiguration or bundle generation
    errors. An over-strict validator that refuses any chain containing
    certs outside the verification path would break these upstreams.
    mitmproxy should find the correct path and silently ignore the rest.
    """

    def test_junk_certs_in_chain_dont_break_verify(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://extra-intermediates.test/ through the proxy returns 200.

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18447 HTTPS endpoint. The sinkhole presents the chain
        [leaf, real intermediate, junk CA A, junk CA B]. Only
        `leaf -> real intermediate -> ca.crt` is on the verification
        path; the two junk CAs are unrelated self-signed certs.
        Why: A green 200 confirms the chain builder picks the right
        path and ignores extras. A red means either the builder got
        confused by the junk, or it rejected the whole chain for
        containing unrelated certs -- either would break real upstreams
        that ship mis-bundled intermediates.
        """
        response = proxy_client.get(
            "https://extra-intermediates.test/",
            follow_redirects=False,
        )
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. mitmproxy failed "
            f"verification despite a valid path existing in the chain -- "
            f"chain builder regression on extras."
        )
        requests = sinkhole.get_requests(host="extra-intermediates.test")
        assert len(requests) >= 1


class TestExpiredLeafRejected:
    """Must-fail: upstream MUST reject a cert whose notAfter is in the past.

    Why: Accepting expired certs has historically regressed in TLS
    stacks (most famously GnuTLS CVE-2014-3466, but also ssl stacks
    whose expiry check lived in a flag disabled by default). If SafeYolo
    ever accepts an expired upstream cert, attackers who compromised an
    expired key long after its issuer stopped caring could impersonate
    the upstream. This test is the canary.
    """

    def test_expired_cert_causes_upstream_failure(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://expired-leaf.test/ through the proxy returns 502 (or errors).

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18448 HTTPS endpoint, which presents a valid chain whose
        leaf has notAfter=2021-01-01 (years in the past). mitmproxy
        walks the chain, validates the signatures (all fine), then
        checks validity windows and MUST reject.
        Why: Any response other than an upstream-verify failure
        (connection error or 502) means SafeYolo accepted an expired
        cert -- a regression that would silently weaken upstream
        authentication across the board.
        """
        _assert_upstream_rejected(
            proxy_client,
            "https://expired-leaf.test/",
            "expired-leaf.test",
            sinkhole,
        )


class TestWrongSanRejected:
    """Must-fail: upstream MUST reject a cert whose SAN doesn't match the host.

    Why: Hostname verification is the most basic TLS invariant after
    chain trust. A bug that accepts any valid-chained cert regardless
    of hostname would let anyone with ANY cert signed by a trusted CA
    impersonate ANY upstream. This test ensures the SAN-match check
    still fires.
    """

    def test_cert_with_mismatched_san_causes_failure(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://wrong-san.test/ through the proxy returns 502 (or errors).

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18449 HTTPS endpoint. The leaf has SAN=DNS:other-name.test
        only -- neither the requested hostname (wrong-san.test) nor the
        connection target IP (127.0.0.1) appears. The chain itself is
        valid, so the only reason to reject is the hostname mismatch.
        Why: Any response other than an upstream-verify failure means
        SafeYolo is accepting certs without checking SAN -- a
        catastrophic regression that breaks TLS authentication entirely.
        """
        _assert_upstream_rejected(
            proxy_client,
            "https://wrong-san.test/",
            "wrong-san.test",
            sinkhole,
        )


class TestSelfSignedLeafRejected:
    """Must-fail: upstream MUST reject a self-signed leaf with no trust path.

    Why: A self-signed leaf whose issuer isn't in the trust store has
    no path to a trusted root. Accepting it would mean anyone with a
    key can generate a cert for any hostname and pass verification.
    This test ensures SafeYolo's trust store isn't being bypassed.
    """

    def test_self_signed_cert_causes_failure(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://self-signed.test/ through the proxy returns 502 (or errors).

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18450 HTTPS endpoint, which presents a single self-signed
        leaf (SAN=self-signed.test, 127.0.0.1). The leaf signs itself;
        no trusted issuer is present in the chain.
        Why: Any response other than an upstream-verify failure means
        SafeYolo is accepting untrusted roots -- TLS trust is broken.
        """
        _assert_upstream_rejected(
            proxy_client,
            "https://self-signed.test/",
            "self-signed.test",
            sinkhole,
        )


class TestAiaOnlyRejected:
    """Must-fail: upstream MUST reject a chain that presents only the leaf.

    Why: When the server omits intermediates, the verifier has no path
    to a trusted root unless it chases the AIA caIssuers URL. Python
    ssl / OpenSSL default to NOT chasing AIA -- servers are expected
    to ship the full chain. mitmproxy inherits that. If it ever flips
    to AIA-chasing (custom verify callback, new OpenSSL flag), an
    attacker who controls the AIA URL or can MITM the HTTP fetch
    could inject arbitrary intermediates -- a silent widening of the
    trust surface. This test documents current "fails deterministically"
    behavior; a 200 here means chain-building policy changed and the
    assertion needs an explicit update.
    """

    def test_missing_intermediate_causes_failure(
        self, proxy_client, sinkhole, clear_sinkhole, wait_for_services,
    ):
        """GET https://aia-only.test/ through the proxy returns 502 (or errors).

        What: Route through SafeYolo's mitmproxy to the sinkhole's
        port-18451 HTTPS endpoint, which presents ONLY the leaf --
        the intermediate is deliberately absent from the chain PEM.
        The leaf's AIA caIssuers extension points at a local URL
        that a future AIA-chaser could hit, but today nothing fetches
        it; chain-building halts at the missing issuer.
        Why: Any response other than an upstream-verify failure means
        mitmproxy started AIA-chasing without an explicit policy
        decision -- a silent, auditable change to what SafeYolo
        accepts as a valid upstream chain.
        """
        _assert_upstream_rejected(
            proxy_client,
            "https://aia-only.test/",
            "aia-only.test",
            sinkhole,
        )
