#!/usr/bin/env python3
"""Render triage-graph YAML files under
`cli/src/safeyolo/agent_context/skills/safeyolo/references/graph/*.yaml`
to sibling `.mmd` (mermaid) files so the human operator can see them at a
glance.

The YAML is the source of truth; the .mmd is a derived render for
readability. Runs deterministically -- same YAML in, same bytes out --
so `git diff --exit-code` after a regenerate is the drift check.

Usage
-----

    scripts/render_skill_graph.py                # render all graphs
    scripts/render_skill_graph.py --check        # exit 1 if any render is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
GRAPH_DIR = REPO_ROOT / "cli/src/safeyolo/agent_context/skills/safeyolo/references/graph"

SHAPE = {
    "symptom": ("([", "])"),          # rounded
    "evidence": ("[", "]"),           # rectangle
    "classification": ("{{", "}}"),   # hexagon
    "conclusion": ("([", "])"),       # stadium (same rounded shape works)
    "operator_ask": ("[[", "]]"),     # subroutine
}


def _sanitize(text: str) -> str:
    # Mermaid is fussy about quotes and pipes inside labels.
    return text.replace('"', "'").replace("|", "/").replace("`", "'")


def _node_line(node: dict) -> str:
    kind = node["kind"]
    open_, close_ = SHAPE.get(kind, ("[", "]"))
    label = _sanitize(node["label"])
    return f'    {node["id"]}{open_}"{label}"{close_}'


def _edge_line(edge: dict) -> str:
    label = edge.get("when", "").strip()
    kind = edge["kind"]
    # Encode edge kind + condition inline so the label carries both.
    if label:
        text = f"{kind}: {_sanitize(label)}"
    else:
        text = kind
    return f'    {edge["from"]} -->|"{text}"| {edge["to"]}'


def _render(graph: dict) -> str:
    lines: list[str] = []
    lines.append("flowchart TD")
    lines.append("    %% Auto-generated by scripts/render_skill_graph.py -- do not edit.")
    lines.append("")

    # Style per node kind so the shapes are also colour-coded when rendered.
    lines.append("    classDef symptom fill:#ffe0e0,stroke:#a44")
    lines.append("    classDef evidence fill:#e0e8ff,stroke:#446")
    lines.append("    classDef classification fill:#fff2cc,stroke:#996")
    lines.append("    classDef conclusion fill:#e0ffe0,stroke:#484")
    lines.append("    classDef operator_ask fill:#f0d0ff,stroke:#748")
    lines.append("")

    by_id: dict[str, dict] = {}
    for node in graph["nodes"]:
        by_id[node["id"]] = node
        lines.append(_node_line(node))

    lines.append("")
    for edge in graph.get("edges", []):
        lines.append(_edge_line(edge))

    lines.append("")
    for node_id, node in by_id.items():
        lines.append(f'    class {node_id} {node["kind"]}')

    entries = graph.get("entries", [])
    if entries:
        lines.append("")
        lines.append("    %% Entry symptoms (bind an observed symptom here)")
        for entry in entries:
            sym = entry["symptom"]
            lines.append(f"    style {sym} stroke-width:3px")

    return "\n".join(lines) + "\n"


def _check_referential_integrity(graph: dict) -> list[str]:
    errors: list[str] = []
    node_ids = {n["id"] for n in graph["nodes"]}
    for edge in graph.get("edges", []):
        for side in ("from", "to"):
            if edge[side] not in node_ids:
                errors.append(f"edge references unknown node id in `{side}`: {edge[side]}")
    for entry in graph.get("entries", []):
        if entry["symptom"] not in node_ids:
            errors.append(f"entry references unknown symptom node id: {entry['symptom']}")
        elif next(n for n in graph["nodes"] if n["id"] == entry["symptom"])["kind"] != "symptom":
            errors.append(f"entry node is not a symptom: {entry['symptom']}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if the rendered .mmd is not byte-identical to what would be regenerated.",
    )
    args = parser.parse_args()

    if not GRAPH_DIR.is_dir():
        print(f"render-skill-graph: no graph dir at {GRAPH_DIR}", file=sys.stderr)
        return 0

    yaml_files = sorted(GRAPH_DIR.glob("*.yaml"))
    if not yaml_files:
        print("render-skill-graph: no graphs found")
        return 0

    exit_code = 0
    for yaml_path in yaml_files:
        with yaml_path.open() as f:
            graph = yaml.safe_load(f)

        errors = _check_referential_integrity(graph)
        if errors:
            print(f"{yaml_path.name}: referential integrity errors:", file=sys.stderr)
            for err in errors:
                print(f"  {err}", file=sys.stderr)
            exit_code = 1
            continue

        rendered = _render(graph)
        mmd_path = yaml_path.with_suffix(".mmd")
        if args.check:
            existing = mmd_path.read_text() if mmd_path.exists() else ""
            if existing != rendered:
                print(
                    f"render-skill-graph: {mmd_path.name} is stale; run scripts/render_skill_graph.py",
                    file=sys.stderr,
                )
                exit_code = 1
        else:
            mmd_path.write_text(rendered)
            print(f"rendered {mmd_path.name} ({len(graph['nodes'])} nodes, {len(graph.get('edges', []))} edges)")

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
